#! /bin/sh
# 3.1
# eg.1
# who | grep u
# who | grep -F u


# 3.2
# 3.2.7
# eg.1
find /home/user/resource/demos/classicShellScripting/chapter03/tolstoy -type d -print |
  sed 's;/home/user/resource/demos/classicShellScripting/chapter03/tolstoy/;/home/user/resource/demos/classicShellScripting/chapter03/lt/;' |
  sed 's/^/mkdir /' |
  sh -x

# eg.2
# find tolstoy/ | sed 's;\(/home\)/tolstoy/;\1/lt/;'


# 3.3
# 3.3.3
# sed '/^#/d' quotas | sort > quotas.sorted
# sed '/^#/d' sales | sort > sales.sorted

# join quotas.sorted sales.sorted
# rm quotas.sorted sales.sorted


# 3.3.4
# 3.3.4.2
# eg.1
# who | awk '{ print $1, $3, $NF }'
# who | awk '{ print $0 }'


# 3.3.4.3
# eg.1
# awk -F: -v 'OFS=**' '{ print $1, $5 }' /etc/passwd


# 3.3.4.4
# eg.1
# awk -F: '{ print "User", $1, "is really", $5 }' /etc/passwd
