#! /bin/sh
# 6.1
# 6.1.1
# eg.1
# hours_per_day=24
# readonly hours_per_day
# echo $hours_per_day

# hours_per_day=25
# echo $hours_per_day


# 6.1.2
# eg.1
# reminder="Time to go to the dentist!"
# sleep 1
# echo _${reminder}_


# 6.1.2.1
# eg.1
# echo ${name:=judith}
# name=hello
# echo ${name:=judith}


# 6.1.2.2
# eg.1
# echo first arg is ${1:-judith}
# echo tenth arg is ${10}

# eg.2
# set -- hello "hi there" greetings
# echo there are $# total arguments
# for i in "$*"
# do echo i is $i
# done

# for i in "$@"
# do echo i is $i
# done


# 6.1.3
# eg.1
# echo $((3 > 2))
# i=5
# echo $((i++)) $i
# echo $((++i)) $i


# 6.2
# 6.2.1
# eg.1
ls
echo $?
ls judith
echo $?
